name: Test

on: [push]

jobs:
  buildAndUpload:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init
    - name: Prepare source tree
      run: scons source
      shell: cmd
    - name: Automated test
      run: scons tests
      shell: cmd
    - name: Build launcher
      run: scons launcher
      shell: cmd
    - name: Upload source
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: .
    - name: Upload launcher
      uses: actions/upload-artifact@v2
      with:
        name: launcher
        path: output/*.exe        