name: Test

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: windows-latest
    permissions:
      # required for all workflows
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        architecture: x86
    - name: Prepare source tree
      run: |
        scons source

      shell: cmd
    - name: Build NVDA
      run: scons launcher
      shell: cmd
    - name: Upload NVDA
      uses: actions/upload-artifact@v4
      with:
        name: NVDA
        path: output
