name: Test

on: [push]

jobs:
  buildAndUpload:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update submodules
      run: git submodule update --init
    - name: Prepare source tree
      run: scons source
      shell: cmd
